apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: bharatchopra/multi-client:1.0.1
      ports:
        - containerPort: 3000
